.\" Sorry for my English 
.\" --Dmitry Yu Okunev <dyokunev@ut.mephi.ru> 0x8E30679C
.\"
.TH PAM_UNSHARE 8 "OCTOBER 2015" Linux "Linux-PAM Manual"
.SH NAME
pam_unshare \- an unshare() PAM module
.SH SYNOPSIS
session optional
.B pam_unshare.so
[...]

.SH DESCRIPTION
.B pam_unshare.so
is a PAM module, that calls
.BR unshare (2)
with specified argument.

.SH OPTIONS
Possible options are:
.RS
CLONE_FILES
.br
CLONE_FS
.br
CLONE_NEWIPC
.br
CLONE_NEWNET
.br
CLONE_NEWNS
.br
CLONE_NEWPID
.br
CLONE_NEWUSER
.br
CLONE_NEWUTS
.br
CLONE_SYSVSEM
.RE
.br
 
.br
For details read
.BR unshare (2).

.SH EXAMPLES
session optional pam_unshare.so CLONE_NEWIPC CLONE_NEWNS

.SH AUTHOR
Dmitry Yu Okunev <dyokunev@ut.mephi.ru> 0x8E30679C
.SH SUPPORT
You can get support on IRC-channel in Freenode "#clsync" or on
github's issue tracking system of
.URL https://github.com/xaionaro/pam_unshare "the pam_unshare repository" .
.SH "SEE ALSO"
.BR unshare (2),
.BR pam (3)

