Document: libpam-ns
Title: Debian libpam-ns Manual
Author: <insert document author here>
Abstract: This manual describes what libpam-ns is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libpam-ns/libpam-ns.sgml.gz

Format: postscript
Files: /usr/share/doc/libpam-ns/libpam-ns.ps.gz

Format: text
Files: /usr/share/doc/libpam-ns/libpam-ns.text.gz

Format: HTML
Index: /usr/share/doc/libpam-ns/html/index.html
Files: /usr/share/doc/libpam-ns/html/*.html
