Document: libpam-unshare
Title: Debian libpam-unshare Manual
Author: <insert document author here>
Abstract: This manual describes what libpam-unshare is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libpam-unshare/libpam-unshare.sgml.gz

Format: postscript
Files: /usr/share/doc/libpam-unshare/libpam-unshare.ps.gz

Format: text
Files: /usr/share/doc/libpam-unshare/libpam-unshare.text.gz

Format: HTML
Index: /usr/share/doc/libpam-unshare/html/index.html
Files: /usr/share/doc/libpam-unshare/html/*.html
